spring:
    datasource:
        #默认数据源配置
        default: 
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/xmodule?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false

    redis:
        #默认使用的Redis配置
        default:
            host: 127.0.0.1
            port: 6379

    #OAuth2客户端配置
    security:
        oauth2:
            #OAuth2客户端配置
            client:
                clock-skew: PT600S
                registration:
                    #Keycloak OAuth2授权服务器配置(由于不在预定义配置CommonOAuth2Provider中出现,此处需要手动配置)
                    clientcreds-client:
                        provider: keycloak
                        client-id: oauth2-client-clientcreds
                        client-secret: 77b4450ee8c64739b11d0f7f31ab5de9
                        authorization-grant-type: client_credentials
                        scope: app
                provider:
                    #Keycloak OAuth2授权服务器配置(由于不在预定义配置CommonOAuth2Provider中出现,此处需要手动配置)
                    keycloak:
                        issuer-uri: http://127.0.0.1:8080/auth/realms/spring-security-oauth2
            #OAuth2资源服务器配置
            resourceserver:
                jwt:
                    issuer-uri: http://127.0.0.1:8080/auth/realms/spring-security-oauth2
