#ory/hydra配置
hydra:
    public-api-url: http://192.168.137.110:4444
    admin-api-url: http://192.168.137.110:4445

spring:
    datasource:
        #默认数据源配置
        default: 
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/xmodule?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
